CREATE OR REPLACE VIEW FANTASY_FOOTBALL.total_stats AS
SELECT pl.player_id,
	pl.player_name, 
	pl.year,
    pl.team,
    pl.age,
    pl.position,
    pl.games_played,
    pl.games_started,
    pa.qb_record,
    pa.completions,
    pa.attempts AS passing_attempts,
    pa.completion_pct,
    pa.passing_yards,
    pa.passing_tds,
    pa.td_percentage,
    pa.interceptions,
    pa.int_percentage,
    pa.first_downs_passing,
    pa.longest_pass,
    pa.yards_per_attempt AS yards_per_throw,
    pa.adj_yards_per_attempt AS adj_yards_per_throw,
    pa.yards_per_completion,
    pa.yards_per_game AS passing_yards_per_game,
    pa.qb_rating,
    pa.qbr,
    pa.sacks_taken,
    pa.sack_yards_lost,
    pa.sack_percentage,
    pa.net_yards_per_pass_attempt,
    pa.adj_net_yards_per_pass_attempt,
    pa.comebacks,
    pa.game_winning_drives,
    re.targets,
    re.receptions,
    re.catch_pct,
    re.receiving_yards,
    re.yards_per_catch,
    re.receiving_tds,
    re.receiving_first_downs,
    re.longest_reception,
    re.yards_per_target,
    re.catches_per_game,
    re.receiving_yards_per_game,
    (IFNULL(re.fumbles,0) + IFNULL(ru.fumbles,0)) / 2 AS total_fumbles,
    ru.rushing_attempts,
    ru.rushing_yards,
    ru.rushing_tds,
    ru.rushing_first_downs,
    ru.longest_rush,
    ru.yards_per_attempt AS yards_per_rush,
    ru.yards_per_game AS rushing_yards_per_game,
    IFNULL(ru.rushing_yards,0) + IFNULL(re.receiving_yards,0) as total_yards,
    IFNULL(ru.rushing_tds,0) + IFNULL(re.receiving_tds,0) as total_tds,
    (IFNULL(re.receptions,0) + (IFNULL(re.receiving_yards,0) * 0.1) + (IFNULL(re.receiving_tds,0) * 6) + (IFNULL(ru.rushing_yards,0) * 0.1) + (IFNULL(ru.rushing_tds,0) * 6) + (IFNULL(pa.passing_yards,0) / 25) + (IFNULL(pa.passing_tds,0) * 6)) as ppr_total_points,
    CONCAT(position, rank() OVER (partition by position, year order by (IFNULL(re.receptions,0) + (IFNULL(re.receiving_yards,0) * 0.1) + (IFNULL(re.receiving_tds,0) * 6) + (IFNULL(ru.rushing_yards,0) * 0.1) + (IFNULL(ru.rushing_tds,0) * 6) + (IFNULL(pa.passing_yards,0) / 25) + (IFNULL(pa.passing_tds,0) * 6))  desc)) AS 'ppr_pos_rank',
	((IFNULL(re.receptions,0) * 0.5) + (IFNULL(re.receiving_yards,0) * 0.1) + (IFNULL(re.receiving_tds,0) * 6) + (IFNULL(ru.rushing_yards,0) * 0.1) + (IFNULL(ru.rushing_tds,0) * 6) + (IFNULL(pa.passing_yards,0) / 25) + (IFNULL(pa.passing_tds,0) * 6)) as half_ppr_total_points,
    CONCAT(position, rank() OVER (partition by position, year order by ((IFNULL(re.receptions,0) * 0.5) + (IFNULL(re.receiving_yards,0) * 0.1) + (IFNULL(re.receiving_tds,0) * 6) + (IFNULL(ru.rushing_yards,0) * 0.1) + (IFNULL(ru.rushing_tds,0) * 6) + (IFNULL(pa.passing_yards,0) / 25) + (IFNULL(pa.passing_tds,0) * 6)) desc)) AS 'half_ppr_pos_rank',
	((IFNULL(re.receiving_yards,0) * 0.1) + (IFNULL(re.receiving_tds,0) * 6) + (IFNULL(ru.rushing_yards,0) * 0.1) + (IFNULL(ru.rushing_tds,0) * 6) + (IFNULL(pa.passing_yards,0) / 25) + (IFNULL(pa.passing_tds,0) * 6)) as std_total_points,
    CONCAT(position, rank() OVER (partition by position, year order by ((IFNULL(re.receiving_yards,0) * 0.1) + (IFNULL(re.receiving_tds,0) * 6) + (IFNULL(ru.rushing_yards,0) * 0.1) + (IFNULL(ru.rushing_tds,0) * 6) + (IFNULL(pa.passing_yards,0) / 25) + (IFNULL(pa.passing_tds,0) * 6)) desc)) AS 'std_pos_rank'
FROM FANTASY_FOOTBALL.players pl
LEFT OUTER JOIN FANTASY_FOOTBALL.receiving re on pl.player_id = re.player_id AND pl.year = re.year
LEFT OUTER JOIN FANTASY_FOOTBALL.rushing ru on pl.player_id = ru.player_id and pl.year = ru.year
LEFT OUTER JOIN FANTASY_FOOTBALL.passing pa on pl.player_id = pa.player_id and pl.year = pa.year
ORDER BY ppr_total_points desc;
